# Generated by Django 5.2.13 on 2026-04-30 08:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("website", models.URLField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_title", models.CharField(max_length=200)),
                ("job_url", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "work_mode",
                    models.CharField(
                        choices=[
                            ("onsite", "Présentiel"),
                            ("hybrid", "Hybride"),
                            ("remote", "Full remote"),
                        ],
                        default="onsite",
                        max_length=20,
                    ),
                ),
                ("salary_min", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_max", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[("EUR", "€"), ("CHF", "CHF")],
                        default="EUR",
                        max_length=3,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("indeed", "Indeed"),
                            ("jobup", "Jobup.ch"),
                            ("swissdevjobs", "SwissDevJobs"),
                            ("welcome", "Welcome to the Jungle"),
                            ("hellowork", "HelloWork"),
                            ("freework", "Free-Work"),
                            ("referral", "Cooptation"),
                            ("direct", "Site carrière direct"),
                            ("headhunter", "Chasseur de tête"),
                            ("spontaneous", "Spontanée"),
                            ("other", "Autre"),
                        ],
                        default="linkedin",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyée"),
                            ("seen", "Vue / accusée"),
                            ("phone_screen", "Pré-entretien RH"),
                            ("technical", "Entretien technique"),
                            ("final", "Entretien final"),
                            ("offer", "Offre reçue"),
                            ("accepted", "Acceptée"),
                            ("rejected", "Refusée"),
                            ("ghosted", "Sans réponse"),
                            ("withdrawn", "Retirée"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_activity_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("next_action_date", models.DateField(blank=True, null=True)),
                ("cv_file", models.FileField(blank=True, upload_to="cvs/%Y/%m/")),
                ("cover_letter", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="applications.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity_at"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("role", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("linkedin", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="applications.application",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("applied", "Candidature envoyée"),
                            ("email_sent", "Email envoyé"),
                            ("email_received", "Email reçu"),
                            ("call", "Appel téléphonique"),
                            ("interview", "Entretien"),
                            ("technical_test", "Test technique"),
                            ("offer", "Offre reçue"),
                            ("rejection", "Refus reçu"),
                            ("status_change", "Changement de statut"),
                            ("note", "Note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["user", "status"], name="application_user_id_55b4e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["user", "next_action_date"],
                name="application_user_id_be159d_idx",
            ),
        ),
    ]
